# Repositories
borRepo: https://github.com/maticnetwork/bor.git
borBranch: develop

heimdallRepo: https://github.com/0xPolygon/heimdall-v2.git
heimdallBranch: develop

contractsRepo: https://github.com/maticnetwork/contracts.git
contractsBranch: mardizzone/node-16

genesisContractsRepo: https://github.com/maticnetwork/genesis-contracts.git
genesisContractsBranch: master

# Defaults
devnetType: docker
defaultStake: 10000
defaultFee: 2000

# L1
ethURL: http://ganache:9545 # use localhost for local deployments
ethHostUser: ubuntu

# Misc
mnemonic: "clock radar mass judge dismiss just intact mind resemble fringe diary casino"

# Heimdall
heimdallChainId: heimdall-4052
heimdallDockerBuildContext: https://github.com/0xPolygon/heimdall-v2.git#develop

# Bor
borChainId: 15005
sprintSize: 64
sprintSizeBlockNumber: 0
blockNumber: '0'
blockTime: '2'
numOfBorValidators: 3
numOfBorSentries: 0
numOfBorArchiveNodes: 0
borDockerBuildContext: https://github.com/maticnetwork/bor.git#develop
devnetBorUsers: ubuntu,ubuntu,ubuntu
devnetBorFlags: config,config,config

# Erigon
numOfErigonValidators: 0
numOfErigonSentries: 0
numOfErigonArchiveNodes: 0
