defaultStake: 10000
defaultFee: 2000
borChainId: 15005
heimdallChainId: heimdall-4052
borBranch: v0.2.16
heimdallBranch: v0.2.10
contractsBranch: jc/v0.3.1-backport
sprintSize: 64
blockNumber: 0,64
blockTime: 2,5
numOfValidators: 1
numOfNonValidators: 1
ethURL: http://172.20.1.100:9545
ethHostUser: ubuntu
devnetType: remote
devnetBorHosts:
  - 172.20.1.100
  - 172.20.1.101
devnetHeimdallHosts:
  - 172.20.1.100
  - 172.20.1.101
devnetBorUsers:
  - ubuntu
  - ubuntu
devnetHeimdallUsers:
  - ubuntu
  - ubuntu
borDockerBuildContext: https://github.com/maticnetwork/bor.git#develop
heimdallDockerBuildContext: https://github.com/maticnetwork/heimdall.git#develop
