defaultStake: 10000
defaultFee: 2000
borChainId: 15005
heimdallChainId: heimdall-4052
borBranch: v0.3.0-beta5
heimdallBranch: v0.3.0-beta2
contractsBranch: mardizzone/pos-880-revert
sprintSize: 64
blockNumber: '0'
blockTime: '2'
numOfValidators: 1
numOfNonValidators: 1
ethURL: http://172.20.1.100:9545
ethHostUser: ubuntu
devnetType: remote
devnetBorHosts:
  - 172.20.1.100
  - 172.20.1.101
devnetHeimdallHosts:
  - 172.20.1.100
  - 172.20.1.101
devnetBorUsers:
  - ubuntu
  - ubuntu
devnetHeimdallUsers:
  - ubuntu
  - ubuntu
borDockerBuildContext: https://github.com/maticnetwork/bor.git#qa
heimdallDockerBuildContext: https://github.com/maticnetwork/heimdall.git#qa
