defaultStake: 10000
defaultFee: 2000
borChainId: 15005
heimdallChainId: heimdall-4052
borBranch: c5569e4da9ebe0ce4e63aec571966c71234f7cfc
heimdallBranch: develop
contractsBranch: c5569e4da9ebe0ce4e63aec571966c71234f7cfc
genesisContractsBranch: mardizzone/node-upgrade
sprintSize: 64
blockNumber: '0'
blockTime: '2'
numOfValidators: 1
numOfNonValidators: 1
ethURL: http://172.20.1.100:9545
ethHostUser: ubuntu
devnetType: remote
devnetBorHosts:
  - 172.20.1.100
  - 172.20.1.101
devnetHeimdallHosts:
  - 172.20.1.100
  - 172.20.1.101
devnetBorUsers:
  - ubuntu
  - ubuntu
devnetHeimdallUsers:
  - ubuntu
  - ubuntu
borDockerBuildContext: https://github.com/maticnetwork/bor.git#develop
heimdallDockerBuildContext: https://github.com/maticnetwork/heimdall.git#develop
