defaultStake: 10000
defaultFee: 2000
borChainId: 15005
heimdallChainId: heimdall-4052
borRepo: https://github.com/maticnetwork/bor.git
borBranch: develop
heimdallRepo: https://github.com/maticnetwork/heimdall.git
heimdallBranch: develop
contractsRepo: https://github.com/AryaLanjewar3005/pos-contracts.git 
contractsBranch: anvil-integration-0.0
genesisContractsRepo: https://github.com/maticnetwork/genesis-contracts.git
genesisContractsBranch: master
sprintSize: 64
sprintSizeBlockNumber: 0
blockNumber: '0'
blockTime: '2'
numOfBorValidators: 1
numOfBorSentries: 1
numOfBorArchiveNodes: 0
numOfErigonValidators: 1
numOfErigonSentries: 1
numOfErigonArchiveNodes: 0
ethURL: http://ec2-xx-xxx-xxx-xx.eu-west-1.compute.amazonaws.com:9545
ethHostUser: ubuntu
devnetType: remote
devnetBorHosts:
  - ec2-xx-xxx-xxx-xx.eu-west-1.compute.amazonaws.com
  - ec2-yy-yyy-yyy-yy.eu-west-1.compute.amazonaws.com
devnetHeimdallHosts:
  - ec2-xx-xxx-xxx-xx.eu-west-1.compute.amazonaws.com
  - ec2-yy-yyy-yyy-yy.eu-west-1.compute.amazonaws.com
devnetBorUsers:
  - ubuntu
  - ubuntu
devnetHeimdallUsers:
  - ubuntu
  - ubuntu
devnetBorFlags:
  - config
  - config
borDockerBuildContext: https://github.com/maticnetwork/bor.git#develop
heimdallDockerBuildContext: https://github.com/maticnetwork/heimdall.git#develop
